version: "3"

services:
  frontend:
    hostname: frontend
    image: frontend:1.0
    ports:
      - "8085:80"
    links:
      - backend
  backend:
    hostname: backend
    image: backend:1.0
    ports:
      - "8000:5000"
